import java.io.{BufferedWriter, File, FileWriter}

object IOUtil {

  def saveHeightmap(rows: Vector[Vector[Double]], filename: String, xSpacing: Double = 1.0, zSpacing: Double = 1.0, yScale: Double = 1.0): Unit = {

    // Give us SOMETHING!
    assert(rows.nonEmpty)
    assert(rows.head.nonEmpty)
    // All rows must have the same length
//    rows foreach println
//    rows.map(_.length) foreach println
    assert(rows.map(_.length).distinct.length == 1)

//    val numRows: Int = rows.length
    val numColumns: Int = rows.head.length

    def getPointObjIndex(rowIndex: Int, colIndex: Int): Int = rowIndex * numColumns + colIndex + 1

    val indexedPointHeights: Vector[(Vector[(Double, Int)], Int)] = rows.map(_.zipWithIndex).zipWithIndex

    val file = new File(filename)
    val bw = new BufferedWriter(new FileWriter(file))

    // Write header
    bw.write(f"# Generated by saveLandscape\n")

    // Write vertices
    indexedPointHeights.foreach({case (row, rowIndex) => row.map({case (pointHeight, colIndex) =>
      bw.write(f"# V${getPointObjIndex(rowIndex, colIndex)}\n")
      bw.write(f"v ${rowIndex.toDouble * xSpacing}%.8f ${pointHeight * yScale}%.8f ${colIndex.toDouble * zSpacing}%.8f\n")
    })})

    // Form faces!!!
    indexedPointHeights.sliding(2).foreach(v => {

      val (curRow, curRowIndex) = v(0)
      val (nextRow, nextRowIndex) = v(1)

      curRow.zip(nextRow).sliding(2).foreach(w => {
        val ((_, aColIndex),(_, dColIndex)) = w(0)
        val ((_, bColIndex), (_, cColIndex)) = w(1)
        val aObjIndex: Int = getPointObjIndex(curRowIndex, aColIndex)
        val bObjIndex: Int = getPointObjIndex(curRowIndex, bColIndex)
        val cObjIndex: Int = getPointObjIndex(nextRowIndex, cColIndex)
        val dObjIndex: Int = getPointObjIndex(nextRowIndex, dColIndex)

        bw.write(f"f $aObjIndex $bObjIndex $cObjIndex $dObjIndex\n")
      })

    })

    bw.close()

  }

}
