import java.awt.Image
import java.awt.image.BufferedImage
import java.io.{BufferedWriter, File, FileWriter}
import javax.imageio.ImageIO

object IOUtil {

  def saveHeightmap(rows: Vector[Vector[Double]], filename: String, xSpacing: Double = 1.0, zSpacing: Double = 1.0, yScale: Double = 1.0): Unit = {

    // Give us SOMETHING!
    assert(rows.nonEmpty)
    assert(rows.head.nonEmpty)
    // All rows must have the same length
//    rows foreach println
//    rows.map(_.length) foreach println
    assert(rows.map(_.length).distinct.length == 1)

//    val numRows: Int = rows.length
    val numColumns: Int = rows.head.length

    def getPointObjIndex(rowIndex: Int, colIndex: Int): Int = rowIndex * numColumns + colIndex + 1

    val indexedPointHeights: Vector[(Vector[(Double, Int)], Int)] = rows.map(_.zipWithIndex).zipWithIndex

    val file = new File(filename)
    val bw = new BufferedWriter(new FileWriter(file))

    // Write header
    bw.write(f"# Generated by saveLandscape\n")

    // Write vertices
    indexedPointHeights.foreach({case (row, rowIndex) => row.map({case (pointHeight, colIndex) =>
      bw.write(f"# V${getPointObjIndex(rowIndex, colIndex)}\n")
      bw.write(f"v ${rowIndex.toDouble * xSpacing}%.8f ${pointHeight * yScale}%.8f ${colIndex.toDouble * zSpacing}%.8f\n")
    })})

    // Form faces!!!
    indexedPointHeights.sliding(2).foreach(v => {

      val (curRow, curRowIndex) = v(0)
      val (nextRow, nextRowIndex) = v(1)

      curRow.zip(nextRow).sliding(2).foreach(w => {
        val ((_, aColIndex),(_, dColIndex)) = w(0)
        val ((_, bColIndex), (_, cColIndex)) = w(1)
        val aObjIndex: Int = getPointObjIndex(curRowIndex, aColIndex)
        val bObjIndex: Int = getPointObjIndex(curRowIndex, bColIndex)
        val cObjIndex: Int = getPointObjIndex(nextRowIndex, cColIndex)
        val dObjIndex: Int = getPointObjIndex(nextRowIndex, dColIndex)

        bw.write(f"f $aObjIndex $bObjIndex $cObjIndex $dObjIndex\n")
      })

    })

    bw.close()

  }

  private val identityFunction: Double => Double = x => x
  def savePNG(rows: Vector[Vector[Double]], filename: String, colors: Vector[Int], widthOverride: Option[Int] = None, heightOverride: Option[Int] = None, adjustmentFunction: Double => Double = identityFunction, normalize: Boolean = false): Unit = {
    val imageWidth = rows.head.length
    val imageHeight = rows.length
    val image = new BufferedImage(imageWidth, imageHeight, BufferedImage.TYPE_INT_ARGB)

    // Have to transpose the data... again.
    val flatData: Vector[Double] = rows.transpose.flatten
    val adjustedData: Vector[Double] = flatData.map(adjustmentFunction)
    val minParam: Double = adjustedData.min
    val maxParam: Double = adjustedData.max
    val paramSpread: Double = maxParam - minParam
    val interpolationParameters: Vector[Double] = if (normalize) adjustedData.map(param => (param - minParam) / paramSpread) else adjustedData

    val pixelArray = interpolationParameters.map(param => {

      if (param == 1.0) {
        colors.last
      } else {
        val fractionalColorIndex: Double = param * (colors.length - 1)
        val lowerColorIndex: Int = fractionalColorIndex.floor.toInt


//        println(f"Interpolation param: $param")
//        println(f"Fractional Color Index: $fractionalColorIndex")
//        println(f"Lower Color Index: $lowerColorIndex")
        val lowerColorInt = colors(lowerColorIndex)
        val upperColorInt = colors(lowerColorIndex + 1)

        case class ARGB(a: Double, r: Double, g: Double, b: Double) {
          def toARGBInt: Int = (a.floor.toInt << 24) + (r.floor.toInt << 16) + (g.floor.toInt << 8) + b.floor.toInt
          def interpolate(other: ARGB, t: Double): ARGB = ARGB(
            a * (1.0 - t) + t * other.a,
            r * (1.0 - t) + t * other.r,
            g * (1.0 - t) + t * other.g,
            b * (1.0 - t) + t * other.b
          )
        }
        object ARGB {
          def apply(argbInt: Int): ARGB = ARGB(
            (argbInt >> 24) & 0xFF,
            (argbInt >> 16) & 0xFF,
            (argbInt >> 8) & 0xFF,
            argbInt & 0xFF
          )
        }

        val interpolatedColor: ARGB = ARGB(lowerColorInt).interpolate(ARGB(upperColorInt), fractionalColorIndex % 1.0)

        interpolatedColor.toARGBInt
      }

    }).toArray

    image.setRGB(0, 0, imageWidth, imageHeight, pixelArray, 0, imageWidth)

    val finalImage: BufferedImage = if (widthOverride.nonEmpty || heightOverride.nonEmpty) {
      val newWidth = widthOverride.getOrElse(imageWidth)
      val newHeight = heightOverride.getOrElse(imageHeight)
      val scaledImage = image.getScaledInstance(newWidth, newHeight, Image.SCALE_DEFAULT)
      val scaledBufferedImage = new BufferedImage(newWidth, newHeight, BufferedImage.TYPE_INT_ARGB)
      val graphics = scaledBufferedImage.createGraphics()
      graphics.drawImage(scaledImage, 0, 0, null)
      graphics.dispose()
      scaledBufferedImage
    } else {
      image
    }
    ImageIO.write(finalImage, "png", new File(filename))
  }

}
